// Generated by `rewrite_dsp.py`.

#pragma once

#include "../../common/gui/plugeditor.hpp"
#include "parameter.hpp"

namespace Steinberg {
namespace Vst {

using namespace VSTGUI;

class Editor : public PlugEditor {
public:
  Editor(void *controller);
  virtual ~Editor() {};

  virtual void valueChanged(CControl *pControl) override;
  void updateUI(Vst::ParamID id, ParamValue normalized) override;

  DELEGATE_REFCOUNT(VSTGUIEditor);

protected:
  bool prepareUI() override;

  bool syncUI(ParamID id, float normalized);

  template<Uhhyou::Style style = Uhhyou::Style::common>
  auto addSmallKnob(CCoord left, CCoord top, CCoord width, CCoord margin, ParamID tag)
  {
    auto height = width - 2 * margin;

    auto knob = new Knob<style>(
      CRect(left + margin, top + margin, left + width, top + width - margin), this, tag, palette);
    knob->setSlitWidth(1.0);
    knob->setValueNormalized(controller->getParamNormalized(tag));
    knob->setDefaultValue(param->getDefaultNormalized(tag));
    frame->addView(knob);
    addToControlMap(tag, knob);

    return knob;
  }

  SharedPointer<XYPad> xypad_macro1_abcd;
  SharedPointer<CControl> widget_macro1_ab_cd;
  SharedPointer<CControl> widget_macro1_ac_bd;
  
  SharedPointer<XYPad> xypad_macro2_abcd;
  SharedPointer<CControl> widget_macro2_ab_cd;
  SharedPointer<CControl> widget_macro2_ac_bd;
  
  SharedPointer<XYPad> xypad_macro3_abcd;
  SharedPointer<CControl> widget_macro3_ab_cd;
  SharedPointer<CControl> widget_macro3_ac_bd;
  
  SharedPointer<XYPad> xypad_macro4_abcd;
  SharedPointer<CControl> widget_macro4_ab_cd;
  SharedPointer<CControl> widget_macro4_ac_bd;
  
  SharedPointer<XYPad> xypad_macro5_abcd;
  SharedPointer<CControl> widget_macro5_ab_cd;
  SharedPointer<CControl> widget_macro5_ac_bd;
  
  SharedPointer<XYPad> xypad_macro6_abcd;
  SharedPointer<CControl> widget_macro6_ab_cd;
  SharedPointer<CControl> widget_macro6_ac_bd;
  
  SharedPointer<XYPad> xypad_macro7_abcd;
  SharedPointer<CControl> widget_macro7_ab_cd;
  SharedPointer<CControl> widget_macro7_ac_bd;
  
  SharedPointer<XYPad> xypad_macro8_abcd;
  SharedPointer<CControl> widget_macro8_ab_cd;
  SharedPointer<CControl> widget_macro8_ac_bd;
  
  

  SharedPointer<XYPad> xypad_xy;
  SharedPointer<XYPad> xypad_xz;
  SharedPointer<XYPad> xypad_zy;
  SharedPointer<CControl> widget_axis1;
  SharedPointer<CControl> widget_axis2;
  SharedPointer<CControl> widget_axis3;
};

} // namespace Vst
} // namespace Steinberg