// Generated by generate_parameter_hpp.py

#include "../common/dsp/constants.hpp"
#include "parameter.hpp"

using namespace SomeDSP;

IntScale<double> Scales::boolScale(0, 1);
LinearScale<double> Scales::aftertouch(0.0, 127.0);
LinearScale<double> Scales::pitchBend(-8192.0, 8191.0);
LinearScale<double> Scales::modulationWheel(0.0, 127.0);

IntScale<double> Scales::freefloatosc(0, 1);
IntScale<double> Scales::positivebendrange(0.0, 127.0);
IntScale<double> Scales::negativebendrange(-127.0, 0.0);
IntScale<double> Scales::portaoff_auto_on(0.0, 2.0);
LinearScale<double> Scales::masterphase(-1.0, 1.0);
LogScale<double> Scales::portamento(0.0, 1.0, 0.5, 0.5);
LinearScale<double> Scales::ab_cd(0.0, 1.0);
LinearScale<double> Scales::ac_bd(0.0, 1.0);
LinearScale<double> Scales::level(-1.0, 1.0);
LinearScale<double> Scales::normfreq(0.0, 1.0);
LinearScale<double> Scales::q(0.0, 10.0);
LinearScale<double> Scales::index(0.0, 1.0);
LinearScale<double> Scales::octave(-8.0, 4.0);
LinearScale<double> Scales::phase(-64.0, 64.0);
SPolyScale<double> Scales::pma(-20.0, 20.0, 0.15);
SPolyScale<double> Scales::pmb(-20.0, 20.0, 0.15);
SPolyScale<double> Scales::pmc(-20.0, 20.0, 0.15);
SPolyScale<double> Scales::pmd(-20.0, 20.0, 0.15);
IntScale<double> Scales::type(0.0, 8.0);
LogScale<double> Scales::attack(0.0, 20.0, 0.5, 10.0);
LogScale<double> Scales::decay(0.0, 20.0, 0.5, 10.0);
LinearScale<double> Scales::sustain(0.0, 1.0);
LogScale<double> Scales::release(0.0, 20.0, 0.5, 10.0);
LinearScale<double> Scales::velsens(0.0, 1.0);
LogScale<double> Scales::lfofreq(0.0, 99.0, 0.5, 49.5);
LinearScale<double> Scales::macro(0.0, 1.0);
LinearScale<double> Scales::uptime(0.0, 20.0);
LinearScale<double> Scales::downtime(0.0, 20.0);
LinearScale<double> Scales::env(-1.0, 1.0);
LinearScale<double> Scales::lfo(-1.0, 1.0);
LinearScale<double> Scales::after_touch(-1.0, 1.0);
LinearScale<double> Scales::note(-1.0, 1.0);
LinearScale<double> Scales::velocity(-1.0, 1.0);
LinearScale<double> Scales::mod_wheel(-1.0, 1.0);
LinearScale<double> Scales::pitch_wheel(-1.0, 1.0);
LinearScale<double> Scales::random(-1.0, 1.0);
