// Generated by generate_parameter_hpp.py

#include "../common/dsp/constants.hpp"
#include "parameter.hpp"

using namespace SomeDSP;

IntScale<double> Scales::boolScale(1);
LinearScale<double> Scales::defaultScale(0.0, 1.0);

IntScale<double> Scales::freefloatosc(1);
LinearScale<double> Scales::masterphase(-1, 1);
IntScale<double> Scales::portaoff_auto_on(2);
LogScale<double> Scales::portamento(0, 1, 0.5, 0.5);
LinearScale<double> Scales::ab_cd(0, 1);
LinearScale<double> Scales::ac_bd(0, 1);
LinearScale<double> Scales::level(-1, 1);
LinearScale<double> Scales::normfreq(0, 1);
LinearScale<double> Scales::q(0, 10);
LinearScale<double> Scales::index(0, 1);
LinearScale<double> Scales::octave(-8, 4);
LinearScale<double> Scales::phase(-64, 64);
LogScale<double> Scales::pma(-20, 20, 0.5, 0.0);
LogScale<double> Scales::pmb(-20, 20, 0.5, 0.0);
LogScale<double> Scales::pmc(-20, 20, 0.5, 0.0);
LogScale<double> Scales::pmd(-20, 20, 0.5, 0.0);
IntScale<double> Scales::type(8);
LogScale<double> Scales::attack(0, 20, 0.5, 10.0);
LogScale<double> Scales::decay(0, 20, 0.5, 10.0);
LinearScale<double> Scales::sustain(0, 1);
LogScale<double> Scales::release(0, 20, 0.5, 10.0);
LinearScale<double> Scales::velsens(0, 1);
LinearScale<double> Scales::envelope_1(0, 1);
LinearScale<double> Scales::envelope0(0, 1);
LinearScale<double> Scales::envelope1(0, 1);
LinearScale<double> Scales::envelope2(0, 1);
LinearScale<double> Scales::envelope3(0, 1);
LogScale<double> Scales::lfofreq(0, 99, 0.5, 49.5);
LinearScale<double> Scales::lfo0(-1, 1);
LinearScale<double> Scales::lfo1(-1, 1);
LinearScale<double> Scales::lfo2(-1, 1);
LinearScale<double> Scales::lfo3(-1, 1);
LinearScale<double> Scales::macro(0, 1);
LinearScale<double> Scales::uptime(0, 20);
LinearScale<double> Scales::downtime(0, 20);
LinearScale<double> Scales::env(0, 1);
LinearScale<double> Scales::lfo(0, 1);
LinearScale<double> Scales::mix(0, 1);
LogScale<double> Scales::freq(0, 24000, 0.5, 12000.0);
LinearScale<double> Scales::gain(0, 1);
LinearScale<double> Scales::gate(0, 1);
